language: python
branches:
    only:
        - master
        - pre-master
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade -qr requirements-tests.txt
    - pip install coveralls
script:
  - make coverage
after_success:
    - coveralls
