language: python
branches:
    only:
        - master
        - pre-master
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -qr requirements-tests.txt
script:
  - make coverage
after_success:
    - coveralls
